### ISSUE TITLE
How do you build it?

### ISSUE THREAD

**Issue by optimizedsms** [jglrxavpok/TinyJVM#1]
How do you build it?
Thank you.

**Comment by jglrxavpok** [comment]
It is a PlatformIO project, so I would suggest you check how you can build
with it (I've only ever used the CMake targets made by PlatformIO inside
CLion)

I also want to warn you that this project is only able to execute a very
simple Hello World program for the moment

Le dim. 26 janv. 2020 à 17:41, optimizedsms <notifications@github.com> a
écrit :

**Comment by optimizedsms** [comment]
Thank you!
